# Generated by Django 4.2.1 on 2023-05-25 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_ordersinwork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrdersInWork',
            new_name='PostAddress',
        ),
        migrations.AddField(
            model_name='order',
            name='post_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.postaddress'),
        ),
    ]
