# Generated by Django 4.2.1 on 2023-05-25 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_ordersinwork_postaddress_order_post_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='postaddress',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
