# Generated by Django 4.2.1 on 2023-05-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_item_mainphoto_item_photo1_item_photo2_item_photo3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='mainPhoto',
        ),
        migrations.AlterField(
            model_name='item',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to='<slug>'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='<slug>'),
        ),
        migrations.AlterField(
            model_name='item',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='<slug>'),
        ),
        migrations.AddField(
            model_name='item',
            name='mainphoto',
            field=models.ImageField(blank=True, null=True, upload_to='<slug>'),
        ),
    ]
