# Generated by Django 4.2.1 on 2023-05-26 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_salecodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.salecodes'),
        ),
    ]
