# Generated by Django 4.2.1 on 2023-05-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_item_sex_alter_item_category_alter_item_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caregory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Категория')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
