# Generated by Django 4.2.1 on 2023-05-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_category_delete_caregory_item_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
