# Generated by Django 4.2.1 on 2023-05-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории товаров'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Промокод', 'verbose_name_plural': 'Промокоды'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказанный товар', 'verbose_name_plural': 'Заказанные товары'},
        ),
        migrations.AlterModelOptions(
            name='postaddress',
            options={'verbose_name': 'Адрес заказа', 'verbose_name_plural': 'Адреса заказов'},
        ),
    ]
